-- RLS設定の無効化（重要）
-- 指示書に従い、全テーブルでRLSを無効化（Service Role Key使用のため）

ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_presets DISABLE ROW LEVEL SECURITY;
ALTER TABLE preset_products DISABLE ROW LEVEL SECURITY;
ALTER TABLE form_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE reservations DISABLE ROW LEVEL SECURITY;
ALTER TABLE reservation_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE notification_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE pickup_windows DISABLE ROW LEVEL SECURITY;